services:
  minio:
    image: minio/minio
    ports:
      - "9020:9000"
      - "9021:9001"
    environment:
      MINIO_ROOT_USER: minio_user_8f3a2c
      MINIO_ROOT_PASSWORD: minio_pass_7b1d4e
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  minio_data:
